# Human read-able name for this site, displayed in the header bar
service_name: CTC Traders phase 5 service guide

# The route that will be used to access this site (with tailing slash)
service_link: /guides/ctc-traders-phase5-service-guide/

# ================================================
# You shouldn't need to edit anything below here
# ================================================

# Host to use for canonical URL generation (without trailing slash)
host: developer.service.hmrc.gov.uk

# Header-related options
show_govuk_logo: true

# Links to show on right-hand-side of header
header_links:
  HMRC Developer Hub: /guides/ctc-traders-phase5-service-guide/
  Documentation: https://developer.service.hmrc.gov.uk/api-documentation/docs/using-the-hub
  Applications: https://developer.service.hmrc.gov.uk/developer/applications
  Support: https://developer.service.hmrc.gov.uk/developer/support

footer_links:
  Accessibility statement: https://www.tax.service.gov.uk/accessibility-statement/hmrc-developer-hub

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: false

# Enables the tracking consent banner
tracking_consent_frontend:
  url: /tracking-consent/tracking.js
  gtm_container: b

# Enable multipage navigation in the sidebar
multipage_nav: false

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 3

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: false
